// Mocks generated by Mockito 5.4.4 from annotations
// in weather_app/test/fav_city_weather_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/core/models/api_response.dart' as _i3;
import 'package:weather_app/core/services/dio/dio_api_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_1 extends _i1.SmartFake implements _i3.ApiResponse {
  _FakeApiResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DioApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioApiService extends _i1.Mock implements _i4.DioApiService {
  MockDioApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.ApiResponse> post({
    required Map<String, dynamic>? body,
    required dynamic url,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [],
          {
            #body: body,
            #url: url,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResponse>.value(_FakeApiResponse_1(
          this,
          Invocation.method(
            #post,
            [],
            {
              #body: body,
              #url: url,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse>);

  @override
  _i5.Future<_i3.ApiResponse> get({required String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {#url: url},
        ),
        returnValue: _i5.Future<_i3.ApiResponse>.value(_FakeApiResponse_1(
          this,
          Invocation.method(
            #get,
            [],
            {#url: url},
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse>);

  @override
  _i5.Future<_i3.ApiResponse> put({
    required Map<String, dynamic>? body,
    required dynamic url,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [],
          {
            #body: body,
            #url: url,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResponse>.value(_FakeApiResponse_1(
          this,
          Invocation.method(
            #put,
            [],
            {
              #body: body,
              #url: url,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResponse>);
}
